### ISSUE TITLE
需要修改默认UART口

### ISSUE THREAD

**Issue by airystar** [c2h2/aria-psp-kernel#4]
新建分支，按照如下分配

UART0,1,2,4 四个AURT口, I2C0,1,2 三个I2C口.
UART和I2C端口参考如下分配：(UART3,UART5 不用)

串口名称     ariaboard PIN名称     ariaboard PIN脚号
UART0_RXD    UART0_RXD/GPIO1_10  58
UART0_TXD    UART0_TXD/GPIO1_11  57
UART1_RXD    UART1_RXD/GPIO0_14  62
UART1_TXD    UART1_TXD/GPIO0_15  61
UART2_RXD    SPI0_SCLK/GPIO0_2   65
UART2_TXD    SPI0_D0/GPIO0_3     63
UART3_RXD    MMC0_DAT1   48
UART3_TXD    MMC0_DAT0   49
UART4_RXD    I2C1_SDA/GPIO1_8    56
UART4_TXD    I2C1_SCL/GPIO1_9    55
UART5_RXD    MDIO_CLK    31
UART5_TXD    MDIO_DATA   32
I2C1_SCL     SPI0_CS0/GPIO0_5    66
I2C1_SDA     SPI0_D1/GPIO0_4     64
I2C2_SCL     UART1_RTSN/GPIO0_13     60
I2C2_SDA     UART1_CTSN/GPIO0_12     59

注意：
1 UART3和MMC0接口复用，使用UART3将不能使用MMC0功能
2 UART5和PHY的pin脚复用，使用UART5将不能使用网络功能。

**Comment by c2h2** [comment]
fixed
